baseURL = 'https://www.brandongogetap.com/'
languageCode = 'en-us'
title = "Brandon Gogetap | Blog"
gitRepo = "https://github.com/bgogetap/brandongogetap.com"
enableGitInfo = true
description = "Hello"
theme = 'loveit'

[author]
  name = "Brandon Gogetap"

[params]
  title = "Brandon Gogetap | Blog"
  description = "Android Development Musings"

  [params.app]
    title = "Brandon Gogetap"

  [params.header]
    [params.header.title]
      name = "Brandon Gogetap | Blog"
    [params.header.subtitle]
      name = "Hello"
      typeit = false

  [params.home.profile]
    subtitle = ""

  [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = true
      Whatsapp = true
      Pinterest = false
      Tumblr = false
      HackerNews = true
      Reddit = true
      VK = false
      Buffer = false
      Xing = false
      Line = false
      Instapaper = false
      Pocket = false
      Flipboard = false
      Weibo = false
      Blogger = false
      Baidu = false
      Odnoklassniki = false
      Evernote = false
      Skype = false
      Trello = false
      Mix = false

  [params.social.youtubecustom]
    id = "BrandonGogetap"
    weight = 1

  [params.social.GitHub]
    id = "bgogetap"
    weight = 2

  [params.social.Mastodon]
    id = "@bgogetap"
    prefix = "https://mastodon.social/"
    title = "Mastodon"
    weight = 3

  [params.social.Twitter]
    id = "@bgogetap"
    weight = 4
